name: Release

permissions:
  contents: write

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always

  RUST_BACKTRACE: full

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build ${{ matrix.target.name }} package
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          [
            { name: aarch64-apple-darwin, os: macos-latest },
            { name: x86_64-unknown-linux-gnu, os: ubuntu-latest },
            { name: x86_64-pc-windows-msvc, os: windows-latest },
          ]
    steps:
      - name: Fetch latest code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
          components: rustfmt, clippy

      - name: Add target
        run: rustup target add ${{ matrix.target.name }}

      - name: Build
        run: cargo build --profile final-release --locked --target ${{ matrix.target.name }}

      - name: Pack (macOS)
        if: matrix.target.os == 'macos-latest'
        run: |
          mv target/${{ matrix.target.name }}/final-release/name_placeholder .
          zip name_placeholder-${{ matrix.target.name }}.zip name_placeholder

      - name: Pack (Windows)
        if: matrix.target.os == 'windows-latest'
        run: |
          mv target/${{ matrix.target.name }}/final-release/name_placeholder.exe .
          Compress-Archive -Path name_placeholder.exe -DestinationPath name_placeholder-${{ matrix.target.name }}.zip

      - name: Pack (Linux)
        if: matrix.target.os == 'ubuntu-latest'
        run: |
          mv target/${{ matrix.target.name }}/final-release/name_placeholder .
          tar -czvf name_placeholder-${{ matrix.target.name }}.tar.gz name_placeholder

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: name_placeholder-${{ matrix.target.name }}
          path: name_placeholder-${{ matrix.target.name }}.*
          retention-days: 1

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish
  #       uses: softprops/action-gh-release@v3
  #       with:
  #         discussion_category_name: Announcements
  #         generate_release_notes: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Prepare release artifacts
        run: |
          mkdir -p artifacts
          mv name_placeholder-*/* artifacts/

      - name: Publish
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          discussion_category_name: Announcements
          generate_release_notes: true
          files: artifacts/*

  publish-on-crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
          components: rustfmt, clippy

      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish
        run: cargo publish --locked
